lidar_odometry_node:
  ros__parameters:
    # Sensor parameters
    sensor_hz: 10.0
    min_range: 0.7
    max_range: 120.0
    deskew: false
    # MAD-ICP algorithm parameters
    b_max: 0.2       # [m] max size of kd leaves
    b_min: 0.1       # [m] when a node is flatter than this param, propagate normal
    b_ratio: 0.02    # increase factor of search radius needed in data association
    p_th: 0.8        # [%] ensuring an update when curr point cloud is registered less than this param
    rho_ker: 0.1     # huber threshold in mad-icp
    num_keyframes: 4  # max number of keyframes kept in the local map
    num_threads: 4    # how many threads to use for icp
    # Processing parameters
    processing_frequency: 50.0  # Hz
    max_processing_queue_size: 3
    # QoS parameters
    queue_size: 10
    # Topic parameters
    input_topic: "/kitti/velo"
    output_odom_topic: "odom"
    output_path_topic: "odom_path"
    output_map_topic: "map"
